# Specify a custom docker image from Docker Hub as your build environment
image: python:3.6.2

pipelines:
  default:
    - step:
        name: Deployment (Test Environment)
        deployment: test
        caches:
          - pip
        script:
          - "[ -f /logs ] || mkdir logs && echo 'Logging directory created'"
          - pip install --upgrade -r requirements.txt
          - chmod 777 main.py
          - python ./main.py
  custom:
    production-deployment:
      - step:
          name: Deployment (Test Environment)
          deployment: test
          caches:
            - pip
          script:
            - "[ -f /logs ] || mkdir logs && echo 'Logging directory created'"
            - pip install --upgrade -r requirements.txt
            - chmod 777 main.py
            - python ./main.py
      - step:
          name: Deployment (Production Environment)
          deployment: production
          caches:
            - pip
          script:
            - "[ -f /logs ] || mkdir logs && echo 'Logging directory created'"
            - pip install --upgrade -r requirements.txt
            - chmod 777 main.py
            - python ./main.py
